### ISSUE TITLE
Make generated iframe tag responsive

### ISSUE THREAD

**Issue by danschalow** [danschalow/ONE-Adserver-Toolbox#1]
Current Tag generated in `index.html`:
```html
<iframe src="ad.html?_ADPATH_&_ADCLICK_" width="300" height="600" scrolling="no" frameborder="0"></iframe>
```

Suggested new Tag:
```html
<iframe src="ad.html?_ADPATH_&_ADCLICK_" style="max-width:100%" width="300" height="600" scrolling="no" frameborder="0"></iframe>
````

~Javascript function~ CSS construct also needs to be included, to maintain the aspect ratio.

**Comment by danschalow** [comment]
h3. CSS Construct

Iframe assumes height of parent. Parent uses `%` value for `padding-bottom` to maintain aspect ratio.


```php
<div style="width:<?= $_POST['width'] ?>; max-width:100%">
	<div data-adtech-iframe>
		<iframe src="ad.html?_ADPATH_&_ADCLICK_" scrolling="no" frameborder="0"></iframe>
	</div>
</div>
```

```css
[data-adtech-iframe] {
	position: relative;
	width: 100%;
	height: 0;
	padding-bottom: <?= $_POST['height'] / $_POST['width'] ?>%;
}

[data-adtech-iframe] iframe {
	position: absolute;
	width: 100%;
	height: 100%;
	left: 0; top: 0;
}
```
